name: counter_app_example
description: "Demonstration of using counter_app as a module with centralized storage."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  counter_app:
    path: ../
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  uuid: ^4.6.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
